/**
 * @file src/modules/solve/mock-data.ts
 * @description Rich mock worksheet data for the solve module.
 */

import type { Worksheet, MCQQuestion, FillBlankQuestion, ShortAnswerQuestion, MatchingQuestion } from './types';

/* ── Worksheet 1: Grade 5, Math, Fractions ───────────────────────── */

export const mathFractionsWorksheet: Worksheet = {
  worksheetId: 'ws-math-fractions-001',
  title: 'Mastering Fractions',
  grade: 5,
  subject: 'Math',
  topic: 'Fractions',
  difficulty: 'medium',
  estimatedTimeSeconds: 900,
  totalPoints: 10,
  questions: [
    {
      id: 'q1',
      number: 1,
      type: 'multiple-choice',
      question: 'What is 1/4 + 1/2?',
      options: [
        { letter: 'A', text: '2/6' },
        { letter: 'B', text: '3/4' },
        { letter: 'C', text: '1/3' },
        { letter: 'D', text: '2/4' },
      ],
      correctAnswer: 'B',
      explanation: 'To add 1/4 + 1/2, convert 1/2 to 2/4. Then 1/4 + 2/4 = 3/4.',
      hint1: 'Try converting both fractions to have the same denominator.',
      hint2: 'The least common denominator of 4 and 2 is 4. What is 1/2 as fourths?',
      difficulty: 'easy',
      points: 1,
    } as MCQQuestion,
    {
      id: 'q2',
      number: 2,
      type: 'multiple-choice',
      question: 'Which fraction is equivalent to 3/5?',
      options: [
        { letter: 'A', text: '5/10' },
        { letter: 'B', text: '6/10' },
        { letter: 'C', text: '9/10' },
        { letter: 'D', text: '3/10' },
      ],
      correctAnswer: 'B',
      explanation: '3/5 = 6/10. Multiply both numerator and denominator by 2: (3x2)/(5x2) = 6/10.',
      hint1: 'Multiply the numerator and denominator by the same number.',
      hint2: 'What number times 5 equals 10? Now multiply the top by that same number.',
      difficulty: 'easy',
      points: 1,
    } as MCQQuestion,
    {
      id: 'q3',
      number: 3,
      type: 'fill-in-the-blank',
      question: 'Complete the equation by filling in the missing number.',
      blankSentence: '2/3 + 1/6 = [BLANK]',
      correctAnswer: '5/6',
      explanation: 'Convert 2/3 to 4/6. Then 4/6 + 1/6 = 5/6.',
      hint1: 'Find a common denominator for 3 and 6.',
      hint2: 'The LCD is 6. Convert 2/3 to sixths: 2/3 = 4/6.',
      difficulty: 'medium',
      points: 1,
    } as FillBlankQuestion,
    {
      id: 'q4',
      number: 4,
      type: 'multiple-choice',
      question: 'What is 3/8 x 4?',
      options: [
        { letter: 'A', text: '12/8' },
        { letter: 'B', text: '3/2' },
        { letter: 'C', text: '7/8' },
        { letter: 'D', text: '3/32' },
      ],
      correctAnswer: 'B',
      explanation: '3/8 x 4 = 12/8 = 3/2 (or 1 1/2). Multiply the numerator by 4, then simplify.',
      hint1: 'Multiply the numerator by the whole number.',
      hint2: '3 x 4 = 12. So you get 12/8. Now simplify by dividing both by 4.',
      difficulty: 'medium',
      points: 1,
    } as MCQQuestion,
    {
      id: 'q5',
      number: 5,
      type: 'short-answer',
      question: 'A pizza is cut into 8 equal slices. Sarah eats 3 slices and Tom eats 2 slices. What fraction of the pizza is left? Write your answer as a fraction.',
      correctAnswer: '3/8',
      explanation: 'Sarah and Tom ate 3 + 2 = 5 slices total. 8 - 5 = 3 slices left. So 3/8 of the pizza remains.',
      hint1: 'First figure out how many slices were eaten in total.',
      hint2: 'They ate 5 slices out of 8. The remaining slices are 8 - 5 = 3.',
      difficulty: 'medium',
      points: 1,
    } as ShortAnswerQuestion,
    {
      id: 'q6',
      number: 6,
      type: 'fill-in-the-blank',
      question: 'Simplify the following fraction to its lowest terms.',
      blankSentence: '8/12 = [BLANK]',
      correctAnswer: '2/3',
      explanation: 'The GCF of 8 and 12 is 4. Divide both by 4: 8/4 = 2, 12/4 = 3. So 8/12 = 2/3.',
      hint1: 'Find the greatest common factor of 8 and 12.',
      hint2: 'The GCF is 4. Divide both the numerator and denominator by 4.',
      difficulty: 'easy',
      points: 1,
    } as FillBlankQuestion,
    {
      id: 'q7',
      number: 7,
      type: 'multiple-choice',
      question: 'Which fraction is greater: 5/8 or 3/5?',
      options: [
        { letter: 'A', text: '5/8' },
        { letter: 'B', text: '3/5' },
        { letter: 'C', text: 'They are equal' },
        { letter: 'D', text: 'Cannot be determined' },
      ],
      correctAnswer: 'A',
      explanation: 'Convert to a common denominator (40): 5/8 = 25/40, 3/5 = 24/40. Since 25 > 24, 5/8 is greater.',
      hint1: 'Convert both fractions so they have the same denominator.',
      hint2: 'The LCD of 8 and 5 is 40. 5/8 = 25/40 and 3/5 = 24/40.',
      difficulty: 'hard',
      points: 1,
    } as MCQQuestion,
    {
      id: 'q8',
      number: 8,
      type: 'short-answer',
      question: 'Mrs. Johnson has 3/4 of a yard of ribbon. She uses 1/3 of a yard for a project. How much ribbon does she have left? Express your answer as a fraction.',
      correctAnswer: '5/12',
      explanation: '3/4 - 1/3 = 9/12 - 4/12 = 5/12. Find the LCD (12), convert, then subtract.',
      hint1: 'This is a subtraction problem: 3/4 - 1/3.',
      hint2: 'The LCD of 4 and 3 is 12. Convert: 3/4 = 9/12 and 1/3 = 4/12.',
      difficulty: 'hard',
      points: 1,
    } as ShortAnswerQuestion,
    {
      id: 'q9',
      number: 9,
      type: 'matching',
      question: 'Match each fraction with its decimal equivalent.',
      pairs: [
        { id: 'p1', left: '1/2', right: '0.5' },
        { id: 'p2', left: '1/4', right: '0.25' },
        { id: 'p3', left: '3/4', right: '0.75' },
        { id: 'p4', left: '1/5', right: '0.2' },
      ],
      correctAnswer: JSON.stringify({ p1: 'p1', p2: 'p2', p3: 'p3', p4: 'p4' }),
      explanation: '1/2 = 0.5, 1/4 = 0.25, 3/4 = 0.75, 1/5 = 0.2. Divide the numerator by the denominator to get the decimal.',
      hint1: 'Divide the top number by the bottom number for each fraction.',
      hint2: 'For example, 1 divided by 2 = 0.5, and 1 divided by 4 = 0.25.',
      difficulty: 'hard',
      points: 1,
    } as MatchingQuestion,
    {
      id: 'q10',
      number: 10,
      type: 'fill-in-the-blank',
      question: 'Convert the mixed number to an improper fraction.',
      blankSentence: '2 1/3 = [BLANK]',
      correctAnswer: '7/3',
      explanation: 'Multiply the whole number by the denominator and add the numerator: 2 x 3 + 1 = 7. Keep the denominator: 7/3.',
      hint1: 'Multiply the whole number by the denominator, then add the numerator.',
      hint2: '2 x 3 = 6, then 6 + 1 = 7. The denominator stays the same.',
      difficulty: 'medium',
      points: 1,
    } as FillBlankQuestion,
  ],
};

/* ── Worksheet 2: Grade 3, Science, Solar System ─────────────────── */

export const scienceSolarSystemWorksheet: Worksheet = {
  worksheetId: 'ws-science-solar-001',
  title: 'Exploring Our Solar System',
  grade: 3,
  subject: 'Science',
  topic: 'Solar System',
  difficulty: 'easy',
  estimatedTimeSeconds: 600,
  totalPoints: 10,
  questions: [
    {
      id: 's1',
      number: 1,
      type: 'multiple-choice',
      question: 'Which planet is closest to the Sun?',
      options: [
        { letter: 'A', text: 'Venus' },
        { letter: 'B', text: 'Mercury' },
        { letter: 'C', text: 'Earth' },
        { letter: 'D', text: 'Mars' },
      ],
      correctAnswer: 'B',
      explanation: 'Mercury is the closest planet to the Sun. It is also the smallest planet in our solar system.',
      hint1: 'Think about the order of planets starting from the Sun.',
      hint2: 'The order is: Mercury, Venus, Earth, Mars...',
      difficulty: 'easy',
      points: 1,
    } as MCQQuestion,
    {
      id: 's2',
      number: 2,
      type: 'multiple-choice',
      question: 'How many planets are in our solar system?',
      options: [
        { letter: 'A', text: '7' },
        { letter: 'B', text: '8' },
        { letter: 'C', text: '9' },
        { letter: 'D', text: '10' },
      ],
      correctAnswer: 'B',
      explanation: 'There are 8 planets in our solar system: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune.',
      hint1: 'Pluto is no longer considered a planet.',
      hint2: 'Count them: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.',
      difficulty: 'easy',
      points: 1,
    } as MCQQuestion,
    {
      id: 's3',
      number: 3,
      type: 'fill-in-the-blank',
      question: 'Complete the sentence about the Sun.',
      blankSentence: 'The Sun is a [BLANK] that gives us light and heat.',
      correctAnswer: 'star',
      explanation: 'The Sun is a star! It is the closest star to Earth and provides the light and heat that makes life possible.',
      hint1: 'Is the Sun a planet? A moon? Something else?',
      hint2: 'The Sun shines just like the tiny lights you see in the night sky.',
      difficulty: 'easy',
      points: 1,
    } as FillBlankQuestion,
    {
      id: 's4',
      number: 4,
      type: 'multiple-choice',
      question: 'Which is the largest planet in our solar system?',
      options: [
        { letter: 'A', text: 'Saturn' },
        { letter: 'B', text: 'Neptune' },
        { letter: 'C', text: 'Jupiter' },
        { letter: 'D', text: 'Uranus' },
      ],
      correctAnswer: 'C',
      explanation: 'Jupiter is the largest planet. It is so big that all the other planets could fit inside it!',
      hint1: 'This planet is famous for its Great Red Spot.',
      hint2: 'It starts with the letter J and is a gas giant.',
      difficulty: 'medium',
      points: 1,
    } as MCQQuestion,
    {
      id: 's5',
      number: 5,
      type: 'short-answer',
      question: 'Name the planet we live on and one reason it is special compared to other planets.',
      correctAnswer: 'Earth',
      explanation: 'We live on Earth! Earth is special because it has liquid water, an atmosphere with oxygen, and the right temperature to support life.',
      hint1: 'Look outside your window. What planet are you standing on?',
      hint2: 'This is the only planet known to have life!',
      difficulty: 'easy',
      points: 1,
    } as ShortAnswerQuestion,
    {
      id: 's6',
      number: 6,
      type: 'multiple-choice',
      question: 'Which planet is known for its beautiful rings?',
      options: [
        { letter: 'A', text: 'Mars' },
        { letter: 'B', text: 'Jupiter' },
        { letter: 'C', text: 'Saturn' },
        { letter: 'D', text: 'Venus' },
      ],
      correctAnswer: 'C',
      explanation: 'Saturn is famous for its beautiful rings made of ice and rock particles orbiting around it.',
      hint1: 'This planet looks like it is wearing a hula hoop!',
      hint2: 'It starts with the letter S and is the 6th planet from the Sun.',
      difficulty: 'medium',
      points: 1,
    } as MCQQuestion,
    {
      id: 's7',
      number: 7,
      type: 'fill-in-the-blank',
      question: 'Fill in the name of the planet.',
      blankSentence: '[BLANK] is called the Red Planet because of its reddish appearance.',
      correctAnswer: 'Mars',
      explanation: 'Mars is called the Red Planet because its surface contains iron oxide (rust), giving it a reddish color.',
      hint1: 'Scientists have sent rovers like Curiosity and Perseverance to explore this planet.',
      hint2: 'It is the 4th planet from the Sun and looks reddish in the night sky.',
      difficulty: 'medium',
      points: 1,
    } as FillBlankQuestion,
    {
      id: 's8',
      number: 8,
      type: 'matching',
      question: 'Match each planet with its description.',
      pairs: [
        { id: 'sp1', left: 'Earth', right: 'Has liquid water and life' },
        { id: 'sp2', left: 'Mars', right: 'The Red Planet' },
        { id: 'sp3', left: 'Jupiter', right: 'Largest planet' },
        { id: 'sp4', left: 'Saturn', right: 'Has beautiful rings' },
      ],
      correctAnswer: JSON.stringify({ sp1: 'sp1', sp2: 'sp2', sp3: 'sp3', sp4: 'sp4' }),
      explanation: 'Earth has water and life, Mars is the Red Planet, Jupiter is the largest, and Saturn has beautiful rings.',
      hint1: 'Think about what makes each planet special and unique.',
      hint2: 'Earth is where we live, Mars is red, Jupiter is huge, and Saturn has rings.',
      difficulty: 'medium',
      points: 1,
    } as MatchingQuestion,
    {
      id: 's9',
      number: 9,
      type: 'short-answer',
      question: 'Why does the Moon appear to change shape during the month? Explain in your own words.',
      correctAnswer: 'phases',
      explanation: 'The Moon does not actually change shape. As it orbits Earth, we see different amounts of its sunlit side. These changes are called lunar phases.',
      hint1: 'Think about how the Sun lights up different parts of the Moon.',
      hint2: 'As the Moon goes around Earth, we see different amounts of the bright side.',
      difficulty: 'hard',
      points: 1,
    } as ShortAnswerQuestion,
    {
      id: 's10',
      number: 10,
      type: 'multiple-choice',
      question: 'What keeps the planets moving around the Sun?',
      options: [
        { letter: 'A', text: 'Wind' },
        { letter: 'B', text: 'Gravity' },
        { letter: 'C', text: 'Magnets' },
        { letter: 'D', text: 'Electricity' },
      ],
      correctAnswer: 'B',
      explanation: 'Gravity is the force that keeps the planets in orbit around the Sun. The Sun\'s gravity pulls on all the planets.',
      hint1: 'This is the same force that keeps your feet on the ground.',
      hint2: 'When you jump, this force pulls you back down. The Sun uses this same force on planets.',
      difficulty: 'hard',
      points: 1,
    } as MCQQuestion,
  ],
};

/* ── Formula Sheets ──────────────────────────────────────────────── */

export interface FormulaSection {
  title: string;
  formulas: { name: string; formula: string; description?: string }[];
}

export const mathFormulas: FormulaSection[] = [
  {
    title: 'Fractions',
    formulas: [
      { name: 'Adding fractions', formula: 'a/b + c/d = (ad + bc) / bd', description: 'Find a common denominator first' },
      { name: 'Subtracting fractions', formula: 'a/b - c/d = (ad - bc) / bd' },
      { name: 'Multiplying fractions', formula: 'a/b x c/d = ac / bd' },
      { name: 'Dividing fractions', formula: 'a/b / c/d = a/b x d/c', description: 'Flip the second fraction and multiply' },
      { name: 'Mixed to improper', formula: 'a b/c = (ac + b) / c' },
    ],
  },
  {
    title: 'Basic Operations',
    formulas: [
      { name: 'Order of operations', formula: 'PEMDAS', description: 'Parentheses, Exponents, Multiply/Divide, Add/Subtract' },
      { name: 'Area of rectangle', formula: 'A = l x w' },
      { name: 'Perimeter of rectangle', formula: 'P = 2l + 2w' },
    ],
  },
  {
    title: 'Decimals & Percents',
    formulas: [
      { name: 'Fraction to decimal', formula: 'Divide numerator by denominator' },
      { name: 'Decimal to percent', formula: 'Multiply by 100' },
      { name: 'Percent to decimal', formula: 'Divide by 100' },
    ],
  },
];

export const scienceFormulas: FormulaSection[] = [
  {
    title: 'Solar System Facts',
    formulas: [
      { name: 'Planet order', formula: 'My Very Educated Mother Just Served Us Nachos', description: 'Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune' },
      { name: 'Earth distance from Sun', formula: '93 million miles (150 million km)' },
      { name: 'Moon cycle', formula: '29.5 days', description: 'Time for one complete lunar cycle' },
    ],
  },
];
