/**
 * @file src/modules/solve/worksheetExport.ts
 * @description Client-side worksheet export: PDF (via print), Word (HTML blob), and print.
 */

import type { Worksheet, Question } from './types';

/* ── Shared HTML builder ─────────────────────────────────────────── */

function questionToHTML(q: Question, showAnswer: boolean): string {
  let optionsHTML = '';

  if (q.type === 'multiple-choice' && 'options' in q) {
    optionsHTML = `<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px 24px;margin-top:8px;">
      ${q.options.map(o => `<div style="padding:6px 0;"><strong>${o.letter}.</strong> ${o.text}</div>`).join('')}
    </div>`;
  } else if (q.type === 'fill-in-the-blank' && 'blankSentence' in q) {
    const display = q.blankSentence.replace('[BLANK]', '<span style="display:inline-block;min-width:100px;border-bottom:2px solid #94a3b8;margin:0 4px;">&nbsp;</span>');
    optionsHTML = `<div style="margin-top:8px;font-size:15px;">${display}</div>`;
  } else if (q.type === 'short-answer') {
    optionsHTML = `<div style="margin-top:8px;border:1px solid #e2e8f0;border-radius:8px;min-height:60px;padding:8px;color:#94a3b8;font-size:13px;">Write your answer here...</div>`;
  } else if (q.type === 'matching' && 'pairs' in q) {
    optionsHTML = `<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px;">
      <div><strong style="font-size:11px;color:#64748b;text-transform:uppercase;">Terms</strong>
        ${q.pairs.map(p => `<div style="padding:6px 0;border-bottom:1px solid #f1f5f9;">${p.left}</div>`).join('')}
      </div>
      <div><strong style="font-size:11px;color:#64748b;text-transform:uppercase;">Match</strong>
        ${q.pairs.map(p => `<div style="padding:6px 0;border-bottom:1px solid #f1f5f9;">${p.right}</div>`).join('')}
      </div>
    </div>`;
  }

  const answerHTML = showAnswer
    ? `<div style="margin-top:8px;padding:8px 12px;background:#f0fdf4;border-radius:8px;border:1px solid rgba(109,184,75,0.2);">
        <strong style="color:#6DB84B;">Answer:</strong> ${q.correctAnswer}
        <div style="margin-top:4px;font-size:13px;color:#64748b;">${q.explanation}</div>
      </div>`
    : '';

  const diffDot = q.difficulty === 'easy' ? '#6DB84B' : q.difficulty === 'medium' ? '#F5C534' : '#ef4444';

  return `
    <div style="margin-bottom:20px;page-break-inside:avoid;">
      <div style="display:flex;align-items:center;gap:8px;margin-bottom:4px;">
        <span style="font-weight:700;color:#64748b;font-size:13px;">Q${q.number}</span>
        <span style="width:8px;height:8px;border-radius:50%;background:${diffDot};"></span>
        <span style="font-size:11px;color:#94a3b8;">${q.points} pt${q.points > 1 ? 's' : ''}</span>
      </div>
      <p style="font-size:15px;font-weight:600;color:#0a0f1e;margin:0 0 4px 0;">${q.question}</p>
      ${optionsHTML}
      ${answerHTML}
    </div>`;
}

function buildHTML(worksheet: Worksheet, showAnswers: boolean): string {
  const title = showAnswers ? `${worksheet.title} — Answer Key` : worksheet.title;
  const questionsHTML = worksheet.questions.map(q => questionToHTML(q, showAnswers)).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap');
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Nunito', sans-serif; color: #0a0f1e; padding: 40px; max-width: 800px; margin: 0 auto; }
    @media print {
      body { padding: 20px; }
      .no-print { display: none !important; }
    }
  </style>
</head>
<body>
  <div style="text-align:center;margin-bottom:32px;padding-bottom:20px;border-bottom:2px solid #e2e8f0;">
    <h1 style="font-size:24px;font-weight:800;margin-bottom:8px;">${title}</h1>
    <div style="display:flex;justify-content:center;gap:12px;flex-wrap:wrap;font-size:13px;color:#64748b;">
      <span style="background:#eff6ff;color:#3D9AE8;padding:2px 10px;border-radius:20px;font-weight:700;">${worksheet.subject}</span>
      <span style="background:#f8fafc;padding:2px 10px;border-radius:20px;border:1px solid #e2e8f0;">${worksheet.topic}</span>
      <span style="background:#eff6ff;color:#3D9AE8;padding:2px 10px;border-radius:20px;">Grade ${worksheet.grade}</span>
      <span>${worksheet.questions.length} questions</span>
      <span>${worksheet.totalPoints} points</span>
    </div>
    <div style="margin-top:12px;">
      <p style="font-size:13px;color:#94a3b8;">Name: _________________________ &nbsp;&nbsp; Date: _____________</p>
    </div>
  </div>
  ${questionsHTML}
  <div style="margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0;text-align:center;font-size:11px;color:#94a3b8;">
    Generated by Learnfyra — AI-Powered Worksheets for Grades 1–10
  </div>
</body>
</html>`;
}

/* ── Export functions ─────────────────────────────────────────────── */

/** Open a print dialog for the worksheet. */
export function printWorksheet(worksheet: Worksheet, showAnswers = false): void {
  const html = buildHTML(worksheet, showAnswers);
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(html);
  win.document.close();
  // Wait for fonts to load, then trigger print
  setTimeout(() => {
    win.focus();
    win.print();
  }, 500);
}

/** Download as a .doc file (HTML with Word-compatible markup). */
export function downloadAsWord(worksheet: Worksheet, showAnswers = false): void {
  const html = buildHTML(worksheet, showAnswers);
  const blob = new Blob([
    `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
    <head><meta charset="UTF-8"><title>${worksheet.title}</title></head>
    <body>${html}</body></html>`
  ], { type: 'application/msword' });

  const filename = showAnswers
    ? `${worksheet.title} - Answer Key.doc`
    : `${worksheet.title}.doc`;

  triggerDownload(blob, filename);
}

/** Download as PDF by printing to PDF (browser native). */
export function downloadAsPDF(worksheet: Worksheet, showAnswers = false): void {
  // Use the same print approach — user can "Save as PDF" from print dialog
  printWorksheet(worksheet, showAnswers);
}

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
